apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: thiexco/django-app:latest
          ports:
            - containerPort: 8585
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: multitenantsaas.settings
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_NAME
              value: DB2
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres-password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
